const memberList = [
  {
    id: 1,
    name: "Prajwal Siwa",
    start_date: "2024-09-09",
    duration: "6 months",
    level: "Intermediate",
    package_type: "Regular",
    image_url: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Anisha Thapa",
    start_date: "2024-09-15",
    duration: "12 months",
    level: "Advanced",
    package_type: "Subscription",
    image_url: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Bikash Sharma",
    start_date: "2024-08-20",
    duration: "3 months",
    level: "Novice",
    package_type: "Regular",
    image_url: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Sujan Gurung",
    start_date: "2024-07-30",
    duration: "6 months",
    level: "Intermediate",
    package_type: "Subscription",
    image_url: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 5,
    name: "Nikita Karki",
    start_date: "2024-09-01",
    duration: "9 months",
    level: "Advanced",
    package_type: "Regular",
    image_url: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: 6,
    name: "Santosh Adhikari",
    start_date: "2024-08-25",
    duration: "1 year",
    level: "Intermediate",
    package_type: "Subscription",
    image_url: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 7,
    name: "Rabina KC",
    start_date: "2024-09-05",
    duration: "6 months",
    level: "Novice",
    package_type: "Regular",
    image_url: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 8,
    name: "Sagar Poudel",
    start_date: "2024-07-20",
    duration: "3 months",
    level: "Intermediate",
    package_type: "Subscription",
    image_url: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 9,
    name: "Krishna Rai",
    start_date: "2024-08-10",
    duration: "12 months",
    level: "Advanced",
    package_type: "Regular",
    image_url: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "Nirjala Tamang",
    start_date: "2024-09-07",
    duration: "6 months",
    level: "Novice",
    package_type: "Subscription",
    image_url: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 10,
    name: "Nirjala Tamang",
    start_date: "2024-09-07",
    duration: "6 months",
    level: "Novice",
    package_type: "Subscription",
    image_url: "https://randomuser.me/api/portraits/women/10.jpg",
  },
];

export default memberList;
